backend/app/models/user.py
from app.extentions import db
from datetime import datetime
from app.models.projects import Project


# mongoengine database model for User
# primary key - ObjectId autogenerated


class User(db.Document):
	name = db.StringField(max_length=120, required=True)
	email = db.EmailField(max_length=50, required=True, unique=True)
	age = db.IntField()
	occupation = db.StringField()
	place = db.StringField()
	projects = db.ListField(db.ReferenceField(Project))
	created_at = db.DateTimeField(default=datetime.now())

backend/app/views/usermgmt.py
from flask import redirect, url_for, render_template
from flask import request, Blueprint, flash
from app.models.user import User
from app.models.projects import Project
from app.views.forms import UserForm
from bson.objectid import ObjectId

# Blueprint to create users and manage user list

user = Blueprint('user', __name__)


@user.route('/')  # landing page redirects to --> list view
def index():
    return redirect(url_for('.userlist'))


@user.route('/list')  # list of users
def userlist():
    doc = User.objects()
    return render_template('user/index.html', users=doc)


@user.route('/create', methods=['POST', 'GET'])  # create user
def createuser():
    form = UserForm()
    projects = Project.objects()
    if projects():
        form.projects.choices = [(proj.id, proj.name) for proj in projects]
    if request.method == 'POST' and form.validate_on_submit():
        usr = User.objects(email=form.email.data).first()
        if usr:
            flash('User email already in use. Choose a different id!', 'danger')
        else:
            useer = User()
            useer.occupation = form.occupation.data
            useer.name = form.username.data
            useer.place = form.place.data
            useer.email = form.email.data
            useer.age = form.age.data
            t = request.form.to_dict(flat=False)
            if t.get('projects'):
                projs = [ObjectId(i) for i in t.get('projects')]
                useer.projects = projs
            useer.save()
            flash('User has been created successfully!', 'success')
            return redirect(url_for('.userlist'))  # render user list view after saving
    return render_template('user/createuser.html', form=form, legend='Create new users here.',
                           title='User Creation', operation='Create')  # rendering user creation form


@user.route('/user/<string:uid>')  #  User read
def showuser(uid):
    doc = User.objects.get_or_404(id=uid)
    if doc:
        return render_template('user/showuser.html', user=doc, projects=doc.projects)
    else:
        return redirect(url_for('user.userlist'))


@user.route('/user/<string:uid>/update', methods=["GET", "POST"])   #  User update
def modifyuser(uid):
    form = UserForm()
    projects = Project.objects()
    if projects():
        form.projects.choices = [(proj.id, proj.name) for proj in projects]
    doc = User.objects.get_or_404(id=uid)
    if form.validate_on_submit():
        user = User.objects(email=form.email.data).first()
        if proj and str(user.id) != str(uid):
            flash('email id already in use. Choose a different id for the project!', 'danger')
        else:
            doc.name = form.username.data
            doc.age = form.age.data
            doc.place = form.place.data
            doc.occupation = form.occupation.data
            doc.email = form.email.data
            t = request.form.to_dict(flat=False)
            if t.get('projects'):
                projs = [ObjectId(i) for i in t.get('projects')]
                doc.projects = projs
            else:
                doc.projects = []
            doc.save()
            flash('User updated successfully!', 'success')
            return redirect(url_for('user.userlist'))
    form.username.data = doc.name
    form.email.data = doc.email
    form.occupation.data = doc.occupation
    form.place.data = doc.place
    form.age.data = doc.age
    if len(doc.projects):
        form.projects.data = [t.id for t in doc.projects]
    return render_template('user/createuser.html', legend='Update your users here.',
                           title='User Updation', operation='Update', form=form)


@user.route('/user/<string:uid>/delete', methods=["GET"])
def deleteuser(uid):                                            # User delete
    try:
        User.objects.get(id=uid).delete()
        return redirect(url_for('user.userlist'))
    except:
        return render_template('Notfound.html')

backend/app/templates/user/createuser.html
{% extends 'base.html' %}
{% block content %}

    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4" style="color:#435d7d;"><b>{{legend}}<b></legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.age.label(class="form-control-label") }}
                    {% if form.age.errors %}
                        {{ form.age(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.age.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.age(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.occupation.label(class="form-control-label") }}
                    {% if form.occupation.errors %}
                        {{ form.occupation(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.occupation.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.occupation(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.place.label(class="form-control-label") }}
                    {% if form.place.errors %}
                        {{ form.place(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.place.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.place(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.projects.label(class="form-control-label") }}
                    {% if form.projects.errors %}
                        {{ form.projects(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.projects.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.projects(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
        <div class="form-group">{{operation}}
            <div>{{ form.submit(class="btn btn-outline-success btn-lg" ) }}</div>
        </div>
        </form>
    </div>

  <!--<form method="post">-->

    <!--<label for="username">Username</label>-->
    <!--<input name="username" id="username" class = "formele" placeholder = "Enter name" required>-->

    <!--<label for="age">Age</label>-->
    <!--<input name="age" id="age" type="number" class = "formele" min="1" max="100" placeholder = "Enter a valid age" required>-->

    <!--<label for="occupation">Occupation</label>-->
    <!--<input name="occupation" id="occupation" class = "formele" placeholder = "Enter an occupation" required>-->

    <!--<label for="place">Place</label>-->
    <!--<input name="place" id="place" class = "formele" placeholder = "Enter location" required>-->

    <!--<label for="projects">Assign Projects</label>-->
    <!--<input type="projects" name="projects" class = "formele" id="projects" placeholder="Comma seperated project names">-->

    <!--<input type="submit" class = "submitbutton" value="Create">-->
  <!--</form>-->
{% endblock content %}

backend/app/templates/user/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-6">
                      <h2><b>Users</b></h2>
                    </div>
                <div class="col-sm-6">
                  <a href="{{ url_for('user.createuser')}}" class="btn btn-success"><i class="material-icons">&#xE147;</i> <span>Add New User</span></a></div>
                </div>
            </div>
          <div>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Place</th>
                        <th>Actions</th>
                    </tr>
                </thead>
            <tbody>
            {% for userr in users %}     
            <tr>
            <td>{{ loop.index |e}}</td>
            <td>{{ userr.name|e }}</td>
            <td>{{ userr.place|e }}</td>
            <td>
                <a href="{{ url_for('user.showuser', uid=userr['id']) }}" class="view" ><i class="material-icons" data-toggle="tooltip" title="View">&#xe417;</i></a>
                <a href="{{ url_for('user.modifyuser', uid=userr['id']) }}" class="edit" ><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
                <a href="{{ url_for('user.deleteuser', uid=userr['id'])}}" class="delete"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
            </td>
            </tr>
            {% else %}
        <table style="width:100%;">
            <tr>
             <th style="width:100%; text-align: center; color: #0B5345;">No users found. Create new users to view them here.</th>
            </tr>
        </table>
            {% endfor %}
            </tbody>
        </table>
          </div>
        </div>
    </div>
{% endblock content%}

backend/app/templates/user/showuser.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-12">
                      <h2><b>User Details</b></h2>
                    </div>
                </div>
            </div>
          <div>
            <table class="table table-striped table-hover">

                <tbody>
                <br>
                <div class="row" style="background-color:#435d7d;text-align:left">
                    <div class="col-sm-6">
                      <h2></h2>
                    </div>
                    <div class="col-sm-6">
                      <h2></h2>
                    </div>
                </div>
                <div class="row" style="background-color:#435d7d;text-align:left">
                    <div class="col-sm-6">
                      <h2>User Name</h2>
                    </div>
                    <div class="col-sm-6">
                      <h2>{{user.name}}</h2>
                    </div>
                </div><br>
                <div class="row" style="background-color:#435d7d;text-align:left">
                <div class="col-sm-6">
                  <h2>Email</h2>
                </div>
                    <div class="col-sm-6">
                  <h2>{{user.email}}</h2>
                </div></div> <br>
                <div class="row" style="background-color:#435d7d;text-align:left">
                <div class="col-sm-6">
                  <h2>Age</h2>
                </div>
                <div class="col-sm-6">
                    <h2>{{user.age}}</h2>
                </div></div><br>
                <div class="row" style="background-color:#435d7d;text-align:left">
                <div class="col-sm-6">
                  <h2>Place</h2>
                </div>
                <div class="col-sm-6">
                  <h2>{{user.place}}</h2>
                </div></div><br>
                <div class="row" style="background-color:#435d7d;text-align:left">
                <div class="col-sm-6">
                  <h2>Occupation</h2>
                </div>
                    <div class="col-sm-6">
                  <h2>{{user.occupation}}</h2>
                </div></div><br>
                <div class="row" style="background-color:#435d7d;text-align:left">
                <div class="col-sm-12">
                  <h2>Projects :</h2>
                </div></div>
                {%for i in projects%}
                <div class="row" style="background-color:#435d7d;text-align:left">
                    {%if i.name%}
                    <div class="col-sm-12" style="text-align:center;">
                        <h2>{{i.name}} <span>:  {{i.description}} <span></h2>
                    </div>
                    {%endif%}
                    </div>
                {% else %}
                <div class="row" style="background-color:#435d7d;text-align:left">
                    <div class="col-sm-12">
                        <h2>No assigned projects.</h2>
                    </div>
                    </div>
                {%endfor%}
                <br>
                </tbody>
            </table>
          </div>
        </div>
    </div>
{% endblock content%}