backend/app/models/projects.py
from app.extentions import db
from datetime import datetime

#model for project
Choices = ('Individual Project', 'Team Project', 'Undecided')


class Project(db.Document):
    project_id = db.StringField(max_length=10, required=True, unique=True)
    name = db.StringField(max_length=40, required=True)
    description = db.StringField(required=True)
    type = db.StringField(choices=Choices, required=True)
    created_at = db.DateTimeField(default=datetime.now())

backend/app/views/projectmgmt.py
from flask import redirect, url_for, render_template
from flask import request, Blueprint, flash
from app.models.projects import Project
from app.views.forms import ProjectForm

# Blueprint to create projects and manage project list

project = Blueprint('project', __name__, url_prefix='/project')


@project.route('/list')  # list of projects
def projectlist():
    doc = Project.objects()
    return render_template('project/projectlist.html', projects=doc)


@project.route('/create', methods=['POST', 'GET'])  # create project
def createproject():
    form = ProjectForm()
    if form.validate_on_submit():
        proj = Project.objects(project_id=request.form['project_id']).first()
        if proj:
            flash('Project id already in use. Choose a different id!', 'danger')
        else:
            proj = Project()
            proj.project_id = request.form['project_id']
            proj.name = request.form['name']
            proj.type = request.form['type']
            proj.description = request.form['description']
            proj.save()
            flash('Project has been created successfully!', 'success')
            return redirect(url_for('project.projectlist'))  # render project list view after saving
    return render_template('project/createproject.html', legend='Create new projects here.',
                           title='Project Creation',operation='Create', form=form)  # rendering project creation form


@project.route('/<string:pid>')
def showproject(pid):
    doc = Project.objects.get_or_404(id=pid)
    if doc:
        return render_template('project/showproject.html', project=doc)


@project.route('/<string:pid>/update', methods=["GET", "POST"])
def modifyproject(pid):
    form = ProjectForm()
    doc = Project.objects(id=pid).first()
    print "Validation status", form.validate_on_submit()
    if form.validate_on_submit():
        proj = Project.objects(project_id=form.project_id.data).first()
        if proj and str(proj.id) != str(pid):
            flash('Project id already in use. Choose a different id for the project!', 'danger')
        else:
            doc.name = form.name.data
            doc.project_id = form.project_id.data
            doc.description = form.description.data
            doc.type = form.type.data
            doc.save()
            flash('Project updated!', 'success')
            return redirect(url_for('project.projectlist'))
    form.name.data = doc.name
    form.project_id.data = doc.project_id
    form.description.data = doc.description
    form.type.data = doc.type
    return render_template('project/createproject.html', legend='Update your projects here.',
                           title='Project Updation', operation='Update', form=form)


@project.route('/<string:pid>/delete', methods=["GET"])
def deleteproject(pid):  # delete an existing project
    try:
        Project.objects.get(id=pid).delete()
        return redirect(url_for('project.projectlist'))
    except:
        flash('Something went wrong', 'danger')
        return redirect(url_for(project.projectlist))

backend/app/templates/project/createproject.html
{% extends 'base.html' %}
{% block content %}

    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4" style="color:#435d7d;"><b>{{legend}}<b></legend>
                <div class="form-group">
                    {{ form.name.label(class="form-control-label") }}
                    {% if form.name.errors %}
                        {{ form.name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.project_id.label(class="form-control-label") }}
                    {% if form.project_id.errors %}
                        {{ form.project_id(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.project_id.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.project_id(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.description.label(class="form-control-label") }}
                    {% if form.description.errors %}
                        {{ form.description(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.description.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.description(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.type.label(class="form-control-label") }}
                    {% if form.type.errors %}
                        {{ form.type(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.type.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.type(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
        <div class="form-group">{{operation}}
            <div>{{ form.submit(class="btn btn-outline-success btn-lg" ) }}</div>
        </div>
        </form>
    </div>

{% endblock content%}

backend/app/templates/project/projectlist.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-6">
                      <h2><b>Projects</b></h2>
                    </div>
                <div class="col-sm-6">
                  <a href="{{ url_for('project.createproject')}}" class="btn btn-success"><i class="material-icons">&#xE147;</i> <span>Add New Project</span></a></div>
                </div>
            </div>
          <div>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Project Id</th>
                        <th>Project Name</th>
                        <th>Actions</th>
                    </tr>
                </thead>
            <tbody>
            {% for proj in projects %}
            <tr>
            <td>{{ loop.index |e}}</td>
            <td>{{ proj.project_id|e }}</td>
            <td>{{ proj.name|e }}</td>
            <td>
                <a href="{{ url_for('project.showproject',   pid=proj['id']) }}" class="view" ><i class="material-icons" data-toggle="tooltip" title="View">&#xe417;</i></a>
                <a href="{{ url_for('project.modifyproject', pid=proj['id']) }}" class="edit" ><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
                <a href="{{ url_for('project.deleteproject', pid=proj['id'])}}" class="delete"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
            </td>
            </tr>
            {% else %}
        <table style="width:100%;">
            <tr>
             <th style="width:100%; text-align: center; color: #0B5345;">No projects found. Create new projects to view them here.</th>
            </tr>
        </table>
            {% endfor %}
            </tbody>
        </table>
          </div>
        </div>
    </div>
{% endblock content%}

backend/app/templates/project/showproject.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-12">
                      <h2><b>Project Details</b></h2>
                    </div>
                </div>
            </div>
          <div>
            <table class="table table-striped table-hover">

                <tbody>
                <br>
                <div class="row" style="background-color:#435d7d;text-align:left">
                    <div class="col-sm-6">
                      <h2></h2>
                    </div>
                    <div class="col-sm-6">
                      <h2></h2>
                    </div>
                </div>
                <div class="row" style="background-color:#435d7d;text-align:left">
                    <div class="col-sm-6">
                      <h2>Project Name</h2>
                    </div>
                    <div class="col-sm-6">
                      <h2>{{project.name}}</h2>
                    </div>
                </div><br>
                <div class="row" style="background-color:#435d7d;text-align:left">
                <div class="col-sm-6">
                  <h2>Project Id</h2>
                </div>
                <div class="col-sm-6">
                    <h2>{{project.project_id}}</h2>
                </div></div><br>
                <div class="row" style="background-color:#435d7d;text-align:left">
                <div class="col-sm-6">
                  <h2>Description</h2>
                </div>
                <div class="col-sm-6">
                  <h2>{{project.description}}</h2>
                </div></div><br>
                <div class="row" style="background-color:#435d7d;text-align:left">
                <div class="col-sm-6">
                  <h2>Type</h2>
                </div>
                    <div class="col-sm-6">
                  <h2>{{project.type}}</h2>
                </div></div>
                <br>
                </tbody>
            </table>
          </div>
        </div>
    </div>
{% endblock content%}