backend/app/views/usermgmt.py
from flask import redirect, url_for, render_template
from flask import request, Blueprint, flash
from app.models.user import User
from app.models.projects import Project
from app.views.forms import UserForm
from bson.objectid import ObjectId

# Blueprint to create users and manage user list

user = Blueprint('user', __name__)


@user.route('/')  # landing page redirects to --> list view
def index():
    return redirect(url_for('.userlist'))


@user.route('/list')  # list of users
def userlist():
    doc = User.objects()
    return render_template('user/index.html', users=doc)


@user.route('/create', methods=['POST', 'GET'])  # create user
def createuser():
    form = UserForm()
    projects = Project.objects()
    if projects():
        form.projects.choices = [(proj.id, proj.name) for proj in projects]
    if request.method == 'POST' and form.validate_on_submit():
        usr = User.objects(email=form.email.data).first()
        if usr:
            flash('User email already in use. Choose a different id!', 'danger')
        else:
            useer = User()
            useer.occupation = form.occupation.data
            useer.name = form.username.data
            useer.place = form.place.data
            useer.email = form.email.data
            useer.age = form.age.data
            t = request.form.to_dict(flat=False)
            if t.get('projects'):
                projs = [ObjectId(i) for i in t.get('projects')]
                useer.projects = projs
            useer.save()
            flash('User has been created successfully!', 'success')
            return redirect(url_for('.userlist'))  # render user list view after saving
    return render_template('user/createuser.html', form=form, legend='Create new users here.',
                           title='User Creation', operation='Create')  # rendering user creation form


@user.route('/user/<string:uid>')  #  User read
def showuser(uid):
    doc = User.objects.get_or_404(id=uid)
    if doc:
        return render_template('user/showuser.html', user=doc, projects=doc.projects)
    else:
        return redirect(url_for('user.userlist'))


@user.route('/user/<string:uid>/update', methods=["GET", "POST"])   #  User update
def modifyuser(uid):
    form = UserForm()
    projects = Project.objects()
    if projects():
        form.projects.choices = [(proj.id, proj.name) for proj in projects]
    doc = User.objects.get_or_404(id=uid)
    if form.validate_on_submit():
        user = User.objects(email=form.email.data).first()
        if proj and str(user.id) != str(uid):
            flash('email id already in use. Choose a different id for the project!', 'danger')
        else:
            doc.name = form.username.data
            doc.age = form.age.data
            doc.place = form.place.data
            doc.occupation = form.occupation.data
            doc.email = form.email.data
            t = request.form.to_dict(flat=False)
            if t.get('projects'):
                projs = [ObjectId(i) for i in t.get('projects')]
                doc.projects = projs
            else:
                doc.projects = []
            doc.save()
            flash('User updated successfully!', 'success')
            return redirect(url_for('user.userlist'))
    form.username.data = doc.name
    form.email.data = doc.email
    form.occupation.data = doc.occupation
    form.place.data = doc.place
    form.age.data = doc.age
    if len(doc.projects):
        form.projects.data = [t.id for t in doc.projects]
    return render_template('user/createuser.html', legend='Update your users here.',
                           title='User Updation', operation='Update', form=form)


@user.route('/user/<string:uid>/delete', methods=["GET"])
def deleteuser(uid):                                            # User delete
    try:
        User.objects.get(id=uid).delete()
        return redirect(url_for('user.userlist'))
    except:
        return render_template('Notfound.html')

backend/app/templates/Notfound.html
<html>
<head>
<style type="text/css">	
	@import url(https://fonts.googleapis.com/css?family=opensans:500);
body{
                background: #33cc99;
                color:#fff;
                font-family: 'Open Sans', sans-serif;
                max-height:700px;
                overflow: hidden;
            }
            .c{
                text-align: center;
                display: block;
                position: relative;
                width:80%;
                margin:100px auto;
            }
            ._404{
                font-size: 220px;
                position: relative;
                display: inline-block;
                z-index: 2;
                height: 250px;
                letter-spacing: 8px;
            }
            ._1{
                text-align:center;
                display:block;
                position:relative;
                letter-spacing: 12px;
                font-size: 4em;
                line-height: 80%;
            }
            ._2{
                text-align:center;
                display:block;
                position: relative;
                font-size: 20px;
            }
            .text{
                font-size: 70px;
                text-align: center;
                position: relative;
                display: inline-block;
                margin: 19px 0px 0px 0px;
                /* top: 256.301px; */
                z-index: 3;
                width: 100%;
                line-height: 1.2em;
                display: inline-block;
            }
           

            .btn{
                background-color: rgb( 255, 255, 255 );
                position: relative;
                display: inline-block;
                width: 358px;
                padding: 5px;
                z-index: 5;
                font-size: 25px;
                margin:0 auto;
                color:#33cc99;
                text-decoration: none;
                margin-right: 10px
            }
            .right{
                float:right;
                width:60%;
            }
            
            hr{
                padding: 0;
                border: none;
                border-top: 5px solid #fff;
                color: #fff;
                text-align: center;
                margin: 0px auto;
                width: 420px;
                height:10px;
                z-index: -10;
            }
            
            hr:after {
                content: "\2022";
                display: inline-block;
                position: relative;
                top: -0.75em;
                font-size: 2em;
                padding: 0 0.2em;
                background: #33cc99;
            }
            
            .cloud {
                width: 350px; height: 120px;

                background: #FFF;
                background: linear-gradient(top, #FFF 100%);
                background: -webkit-linear-gradient(top, #FFF 100%);
                background: -moz-linear-gradient(top, #FFF 100%);
                background: -ms-linear-gradient(top, #FFF 100%);
                background: -o-linear-gradient(top, #FFF 100%);

                border-radius: 100px;
                -webkit-border-radius: 100px;
                -moz-border-radius: 100px;

                position: absolute;
                margin: 120px auto 20px;
                z-index:-1;
                transition: ease 1s;
            }

            .cloud:after, .cloud:before {
                content: '';
                position: absolute;
                background: #FFF;
                z-index: -1
            }

            .cloud:after {
                width: 100px; height: 100px;
                top: -50px; left: 50px;

                border-radius: 100px;
                -webkit-border-radius: 100px;
                -moz-border-radius: 100px;
            }

            .cloud:before {
                width: 180px; height: 180px;
                top: -90px; right: 50px;

                border-radius: 200px;
                -webkit-border-radius: 200px;
                -moz-border-radius: 200px;
            }
            
            .x1 {
                top:-50px;
                left:100px;
                -webkit-transform: scale(0.3);
                -moz-transform: scale(0.3);
                transform: scale(0.3);
                opacity: 0.9;
                -webkit-animation: moveclouds 15s linear infinite;
                -moz-animation: moveclouds 15s linear infinite;
                -o-animation: moveclouds 15s linear infinite;
            }
            
            .x1_5{
                top:-80px;
                left:250px;
                -webkit-transform: scale(0.3);
                -moz-transform: scale(0.3);
                transform: scale(0.3);
                -webkit-animation: moveclouds 17s linear infinite;
                -moz-animation: moveclouds 17s linear infinite;
                -o-animation: moveclouds 17s linear infinite; 
            }

            .x2 {
                left: 250px;
                top:30px;
                -webkit-transform: scale(0.6);
                -moz-transform: scale(0.6);
                transform: scale(0.6);
                opacity: 0.6; 
                -webkit-animation: moveclouds 25s linear infinite;
                -moz-animation: moveclouds 25s linear infinite;
                -o-animation: moveclouds 25s linear infinite;
            }

            .x3 {
                left: 250px; bottom: -70px;

                -webkit-transform: scale(0.6);
                -moz-transform: scale(0.6);
                transform: scale(0.6);
                opacity: 0.8; 

                -webkit-animation: moveclouds 25s linear infinite;
                -moz-animation: moveclouds 25s linear infinite;
                -o-animation: moveclouds 25s linear infinite;
            }

            .x4 {
                left: 470px; botttom: 20px;

                -webkit-transform: scale(0.75);
                -moz-transform: scale(0.75);
                transform: scale(0.75);
                opacity: 0.75;

                -webkit-animation: moveclouds 18s linear infinite;
                -moz-animation: moveclouds 18s linear infinite;
                -o-animation: moveclouds 18s linear infinite;
            }

            .x5 {
                left: 200px; top: 300px;

                -webkit-transform: scale(0.5);
                -moz-transform: scale(0.5);
                transform: scale(0.5);
                opacity: 0.8; 

                -webkit-animation: moveclouds 20s linear infinite;
                -moz-animation: moveclouds 20s linear infinite;
                -o-animation: moveclouds 20s linear infinite;
            }

            @-webkit-keyframes moveclouds {
                0% {margin-left: 1000px;}
                100% {margin-left: -1000px;}
            }
            @-moz-keyframes moveclouds {
                0% {margin-left: 1000px;}
                100% {margin-left: -1000px;}
            }
            @-o-keyframes moveclouds {
                0% {margin-left: 1000px;}
                100% {margin-left: -1000px;}
            }
</style>
</head>
<body>
	<div id="clouds">
            <div class="cloud x1"></div>
            <div class="cloud x1_5"></div>
            <div class="cloud x2"></div>
            <div class="cloud x3"></div>
            <div class="cloud x4"></div>
            <div class="cloud x5"></div>
        </div>
        <div class='c'>
            <div class='_404'>Oops</div>
            <hr>
            <div class='_1'>Something wrong</div>
            <div class='_2'>here</div>
            <a class='btn' href="{{ url_for('user.index') }}">BACK TO HOME</a>
        </div>
</body>

</html>

backend/app/templates/base.html
<!doctype html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Flask App</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script type="text/javascript">
    $(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();});
  </script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css')}}">
</head>
<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="/">Management</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('user.index') }}" class="view">Manage Users</a>
              <a class="nav-item nav-link" href="{{ url_for('project.projectlist') }}" class="view">Manage Projects</a>
          </div>
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}">
                  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        {% if title %}
        <h2 style="text-align:center;color:#435d7d;">{{title}}</h2>
        {% endif %}
        {% block content %}{% endblock %}
        </div>
        <div class="col-md-1"></div>
    </div>
  </main>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>